version: '3'
services:
  s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=s3MinIOadmin
    volumes:
      - s3_volume:/data
    command: server /data --console-address ':9001' --address ':9000'
    restart: unless-stopped
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mlflow_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: unless-stopped
  mlflow:
    depends_on:
      - postgres
    build: .
    ports:
      - 5000:5000
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=s3MinIOadmin
    command: mlflow server --backend-store-uri postgresql://admin:admin@postgres:5432/mlflow_db --default-artifact-root s3://mlflow/ --host 0.0.0.0 --port 5000
volumes:
    postgres_volume:
    s3_volume:
