apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: mlflow-server
  template:
    metadata:
      labels:
        tag: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: vchraf/mlflow-server:v1
          command: ["mlflow server"]
          args:
          - --host=0.0.0.0
          - --port=5000
          - --backend-store-uri postgresql://admin:admin@postgres:5432/mlflow_db
          - --default-artifact-root s3://mlflow/
          - --workers=1
          port:
            - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minios3:9000
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: s3MinIOadmin
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server-clusterip
spec:
  type: ClusterIP
  selector:
    tag: mlflow-server
  ports:
    - port: 5000
      targetPort: 5000
