apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: mlflow-server
  template:
    metadata:
      labels:
        tag: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: vchraf/mlflow-server:v2
          args: ["--backend-store-uri","postgresql://admin:admin@mlflow-postgres-clusterip:5432/mlflow_db","--default-artifact-root","s3://mlflow/","--host","0.0.0.0","--port","5775","--workers=1"]
          ports:
            - containerPort: 5775
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /mlflow
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://mlflow-minio-service-clusterip:9000
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: s3MinIOadmin
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server-clusterip
spec:
  type: ClusterIP
  selector:
    tag: mlflow-server
  ports:
  - name: http
    port: 5775
    protocol: TCP
    targetPort: 5775
